# 1.0 — Setup & Imports

Mounts Google Drive, imports all required libraries, and seeds all random number generators for reproducibility.

## 1.1 — Google Drive & Library Imports

In [1]:
# Environment detection & optional Colab mount
import sys
if 'google.colab' in sys.modules:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=False)

# Standard library
import os
import json
import time
import random
import io
import gc
import subprocess
from pathlib import Path

from scipy.io import loadmat

# Defensive package verification / installation
for pkg in ['openpyxl', 'pillow']:
    try:
        __import__(pkg)
    except ImportError:
        subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', pkg], check=True)

# Numerical / data
import numpy as np
import pandas as pd

# Visualisation (headless backend configured before importing pyplot)
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import seaborn as sns

# Deep learning
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, regularizers

# GPU Dynamic Memory Growth Configuration
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    for gpu in gpus:
        try:
            tf.config.experimental.set_memory_growth(gpu, True)
        except RuntimeError as e:
            print(f"Memory growth error: {e}")
    print(f"GPU Active: {len(gpus)} device(s) detected: {[g.name for g in gpus]}")
else:
    print("WARNING: No physical GPU detected!")

# Enable Keras unsafe deserialization for custom layer loading
try:
    keras.config.enable_unsafe_deserialization()
    print("Keras unsafe deserialization enabled.")
except Exception as e:
    print(f"Notice: keras.config.enable_unsafe_deserialization(): {e}")

# Scikit-learn
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    cohen_kappa_score,
    confusion_matrix,
    classification_report,
    f1_score,
    log_loss,
)

# Excel export
from openpyxl import Workbook, load_workbook
from openpyxl.drawing.image import Image as XLImage

sns.set_style('whitegrid')
print('Python:    ', sys.version.split()[0])
print('TensorFlow:', tf.__version__)
print('Keras:     ', keras.__version__)

GPU Active: 1 device(s) detected: ['/physical_device:GPU:0']
Keras unsafe deserialization enabled.
Python:     3.12.13
TensorFlow: 2.20.0
Keras:      3.13.2

## 1.2 — Seed Initialisation

Sets the global random seed across Python, NumPy, and TensorFlow to ensure reproducible runs.

In [2]:
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

# 2.0 — Configuration

All project paths, dataset geometry, training hyperparameters, and per-architecture configs are defined here. Change values in this section only — nothing below should need editing for typical experiments.

## 2.1 — Paths & Directories

In [3]:
IN_KAGGLE = Path('/kaggle').exists() or Path('/kaggle/working').exists()
IN_COLAB  = 'google.colab' in sys.modules

if IN_KAGGLE:
    k001_primary = Path('/kaggle/input/dias-dataset-k01/k001.mat')
    k002_primary = Path('/kaggle/input/dias-dataset-k01/k002.mat')
    if k001_primary.exists() and k002_primary.exists():
        DATA_FILE  = k001_primary
        LABEL_FILE = k002_primary
        DATA_DIR   = k001_primary.parent
    else:
        dias_candidates = (
            list(Path('/kaggle/input').glob('**/k001.mat')) or
            list(Path('/kaggle/input').glob('**/DIAS.mat'))
        )
        ref_candidates = (
            list(Path('/kaggle/input').glob('**/k002.mat')) or
            list(Path('/kaggle/input').glob('**/DIAS_ref.mat'))
        )
        DATA_FILE  = dias_candidates[0] if dias_candidates else k001_primary
        LABEL_FILE = ref_candidates[0] if ref_candidates else k002_primary
        DATA_DIR   = DATA_FILE.parent

    OUTPUT_ROOT = Path('/kaggle/working/results')
    MODEL_DIR   = OUTPUT_ROOT / 'models'
    PLOT_DIR    = OUTPUT_ROOT / 'training_plots'
    VIS_DIR     = OUTPUT_ROOT / 'scene_visualizations'
elif IN_COLAB:
    PROJECT_ROOT = Path('/content/drive/My Drive/Classification/')
    DATA_DIR     = PROJECT_ROOT / 'data'
    DATA_FILE    = DATA_DIR / 'DIAS.mat'
    LABEL_FILE   = DATA_DIR / 'DIAS_ref.mat'
    OUTPUT_ROOT  = PROJECT_ROOT / 'ensemble' / 'results'
    MODEL_DIR    = PROJECT_ROOT / 'ensemble' / 'models'
    PLOT_DIR     = MODEL_DIR / 'training_plots'
    VIS_DIR      = MODEL_DIR / 'scene_visualizations'
else:
    PROJECT_ROOT = Path.cwd()
    DATA_DIR     = Path('data') if Path('data').exists() else PROJECT_ROOT / 'data'
    DATA_FILE    = DATA_DIR / 'DIAS.mat' if (DATA_DIR / 'DIAS.mat').exists() else DATA_DIR / 'k001.mat'
    LABEL_FILE   = DATA_DIR / 'DIAS_ref.mat' if (DATA_DIR / 'DIAS_ref.mat').exists() else DATA_DIR / 'k002.mat'
    OUTPUT_ROOT  = Path('ensemble/results')
    MODEL_DIR    = OUTPUT_ROOT / 'models'
    PLOT_DIR     = OUTPUT_ROOT / 'training_plots'
    VIS_DIR      = OUTPUT_ROOT / 'scene_visualizations'

OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
MODEL_DIR.mkdir(parents=True, exist_ok=True)
PLOT_DIR.mkdir(parents=True, exist_ok=True)
VIS_DIR.mkdir(parents=True, exist_ok=True)

VIS_EXCEL_PATH = VIS_DIR / 'initial_classification_maps.xlsx'

print('Environment: ', 'Kaggle' if IN_KAGGLE else ('Colab' if IN_COLAB else 'Local'))
print('Data file  :', DATA_FILE, f'(exists: {DATA_FILE.exists()})')
print('Label file :', LABEL_FILE, f'(exists: {LABEL_FILE.exists()})')
print('Output dir :', OUTPUT_ROOT)
print('Model dir  :', MODEL_DIR)
print('Plot dir   :', PLOT_DIR)
print('Vis dir    :', VIS_DIR)

Environment:  Kaggle
Data file  : /kaggle/input/datasets/daneshselwal/dias-dataset-k01/k001.mat (exists: True)
Label file : /kaggle/input/datasets/daneshselwal/dias-dataset-k01/k002.mat (exists: True)
Output dir : /kaggle/working/results
Model dir  : /kaggle/working/results/models
Plot dir   : /kaggle/working/results/training_plots
Vis dir    : /kaggle/working/results/scene_visualizations

## 2.2 — Dataset & Training Hyperparameters

In [4]:
# H, W, B are inferred automatically from the .mat cube shape once loaded in
# Section 3.2, so this notebook works unchanged for any scene size / band count.
H, W, B     = None, None, None
PERCENTILE_CLIP = (2.0, 98.0)  # robust per-band stretch range (2nd-98th percentile)
PATCH_SIZE  = 9
INNER_PATCH = 3   # used by GFNet/ViT tokenisation

TRAIN_PERCENT          = 0.75
VAL_SPLIT_FROM_TRAIN   = 0.20

BATCH_SIZE    = 128
EPOCHS        = 100
LEARNING_RATE = 3e-4
DROPOUT_RATE  = 0.25

TRAIN_CFG = {
    'label_smoothing': 0.05,
    'weight_decay':    1e-4,
    'clipnorm':        1.0,
    'cosine_alpha':    0.05,
}

## 2.3 — Architecture Configs (Primary & Fallback)

In [5]:
CAPACITY_PRESET = 'legacy_arch'

ALEXNET_CFG = {
    'conv_filters': [96, 256, 384, 384, 256],
    'dense_units':  [4096, 1024, 256, 32],
}

GFNET_CFG = {
    'hidden_dim': 512,
    'num_blocks': 5,
    'mlp_ratio':  4,
}

VIT_CFG = {
    'projection_dim':    256,
    'num_heads':         4,
    'transformer_layers': 12,
    'mlp_multiplier':    2,
    'head_units':        [512, 256, 128, 64],
}

# Deterministic fallback configs if Colab runs out of memory
GFNET_FALLBACK_CFG = {
    'hidden_dim': 384,
    'num_blocks': 4,
    'mlp_ratio':  4,
}

VIT_FALLBACK_CFG = {
    'projection_dim':    192,
    'num_heads':         4,
    'transformer_layers': 8,
    'mlp_multiplier':    2,
    'head_units':        [384, 192, 96, 64],
}

print('Architecture preset:', CAPACITY_PRESET)

Architecture preset: legacy_arch

## 2.4 — AlexNet Legacy Training Config

Separate learning-rate settings for AlexNet, matching the original single-head script for uncertainty recovery.

In [6]:
ALEXNET_LEGACY_SPLIT_SEED     = 10
ALEXNET_LEGACY_TRAIN_PERCENT  = 0.75
ALEXNET_LR_START = 0.01
ALEXNET_LR_MAX   = 0.02
ALEXNET_LR_MIN   = 0.005

## 2.5 — Visualisation Palette

In [7]:
CLASS_COLOR_BASE = [
    '#0000FF', '#00FF00', '#FF0000', '#00FFFF',
    '#FF00FF', '#FFFF00', '#A52A2A', '#FFA500',
    '#7FFF00', '#8A2BE2',
]
BACKGROUND_COLOR = '#000000'

import colorsys

def _generate_extra_shades(n_extra, hue_offset=0.05, sat=0.85, val=0.95):
    """Bold, highly-saturated extra hues in the same style as CLASS_COLOR_BASE,
    for datasets with more than 10 classes."""
    shades = []
    for i in range(n_extra):
        hue = (hue_offset + i / max(n_extra, 1)) % 1.0
        r, g, b = colorsys.hsv_to_rgb(hue, sat, val)
        shades.append('#%02x%02x%02x' % (int(r * 255), int(g * 255), int(b * 255)))
    return shades

def get_class_colors(n):
    """Return n distinct hex colours, extending the base 10 with additional bold
    shades in the same saturated style if needed."""
    if n <= len(CLASS_COLOR_BASE):
        return CLASS_COLOR_BASE[:n]
    return CLASS_COLOR_BASE + _generate_extra_shades(n - len(CLASS_COLOR_BASE))

# 3.0 — Data Loading & Preprocessing

Loads the hyperspectral/multispectral scene and labels from .mat files, robustly normalises per-band via percentile clip, extracts labeled patches, and creates train/val/test splits.

## 3.1 — Data Loading & Patch Extraction Functions

In [8]:
def load_scene_from_mat(data_path, label_path, data_key=None, label_key=None):
    """Load a hyperspectral/multispectral scene + reference labels from .mat files.

    Auto-detects the variable name inside each .mat file if not given (matches
    files such as DIAS.mat / DIAS_ref.mat storing the array under a single
    named variable). Each spectral band is robustly stretched to [0, 1] using
    a percentile clip (PERCENTILE_CLIP) rather than literal min/max — a handful
    of saturated/no-data pixels (e.g. sensor clipping at int8 range limits
    -128/127) would otherwise dominate the stretch.
    """
    def _first_array(mat_dict, key):
        if key is not None:
            return mat_dict[key]
        candidates = [v for k, v in mat_dict.items() if not k.startswith('__')]
        if not candidates:
            raise ValueError(f'No data arrays found in {mat_dict.keys()}')
        return candidates[0]

    data_mat  = loadmat(data_path)
    label_mat = loadmat(label_path)

    x = _first_array(data_mat, data_key).astype(np.float32)
    y = _first_array(label_mat, label_key).astype(np.int32)

    if x.ndim != 3:
        raise ValueError(f'Expected a (H, W, Bands) cube, got shape {x.shape}')
    if y.shape != x.shape[:2]:
        raise ValueError(f'Label shape {y.shape} does not match image shape {x.shape[:2]}')

    height, width, bands = x.shape

    x_norm = np.empty_like(x, dtype=np.float32)
    for b in range(bands):
        band = x[:, :, b]
        lo   = np.percentile(band, PERCENTILE_CLIP[0])
        hi   = np.percentile(band, PERCENTILE_CLIP[1])
        denom = max(hi - lo, 1e-8)
        band_clipped = np.clip(band, lo, hi)
        x_norm[:, :, b] = (band_clipped - lo) / denom

    return x_norm, y, height, width, bands


def extract_labeled_patches(x, y, patch_size=9):
    """Extract fixed-size patches centred on every labeled (non-zero) pixel."""
    pad   = patch_size // 2
    x_pad = np.pad(x, ((pad, pad), (pad, pad), (0, 0)), mode='edge')

    coords  = np.argwhere(y > 0)
    patches = np.empty((coords.shape[0], patch_size, patch_size, x.shape[-1]), dtype=np.float32)
    labels  = np.empty((coords.shape[0],), dtype=np.int32)

    for i, (r, c) in enumerate(coords):
        patches[i] = x_pad[r:r + patch_size, c:c + patch_size, :]
        labels[i]  = int(y[r, c]) - 1   # convert class IDs to 0..C-1

    return patches, labels, coords

## 3.2 — Load Dataset

In [9]:
x_img, y_img, H, W, B = load_scene_from_mat(DATA_FILE, LABEL_FILE)
X, y, coords = extract_labeled_patches(x_img, y_img, PATCH_SIZE)

num_classes = int(np.unique(y).size)
input_shape = (PATCH_SIZE, PATCH_SIZE, B)

print('Scene geometry: H=%d  W=%d  Bands=%d' % (H, W, B))
print('x_img:', x_img.shape, '  y_img:', y_img.shape)
print('Labeled samples:', X.shape[0])
print('Patch tensor:', X.shape)
print('Num classes:', num_classes)

Scene geometry: H=512  W=512  Bands=65
x_img: (512, 512, 65)   y_img: (512, 512)
Labeled samples: 53893
Patch tensor: (53893, 9, 9, 65)
Num classes: 8

## 3.3 — Train / Val / Test Splits

Creates the primary stratified splits used by GFNet and ViT, plus the legacy split used by AlexNet to match original script behaviour.

In [10]:
# Primary split (GFNet / ViT)
x_train_full, x_test, y_train_full, y_test = train_test_split(
    X, y, train_size=TRAIN_PERCENT, random_state=SEED, stratify=y,
)
x_train, x_val, y_train, y_val = train_test_split(
    x_train_full, y_train_full,
    test_size=VAL_SPLIT_FROM_TRAIN, random_state=SEED, stratify=y_train_full,
)

y_train_cat = keras.utils.to_categorical(y_train, num_classes)
y_val_cat   = keras.utils.to_categorical(y_val,   num_classes)
y_test_cat  = keras.utils.to_categorical(y_test,  num_classes)

print('Train:', x_train.shape, y_train.shape)
print('Val  :', x_val.shape,   y_val.shape)
print('Test :', x_test.shape,  y_test.shape)

# AlexNet legacy split (matches old single-head script behaviour)
x_train_alex, x_test_alex, y_train_alex, y_test_alex = train_test_split(
    X, y,
    train_size=ALEXNET_LEGACY_TRAIN_PERCENT,
    random_state=ALEXNET_LEGACY_SPLIT_SEED,
    stratify=y,
)
y_train_alex_cat = keras.utils.to_categorical(y_train_alex, num_classes)
y_test_alex_cat  = keras.utils.to_categorical(y_test_alex,  num_classes)

print('AlexNet Train/Test:', x_train_alex.shape, y_train_alex.shape,
      x_test_alex.shape, y_test_alex.shape)

Train: (32335, 9, 9, 65) (32335,)
Val  : (8084, 9, 9, 65) (8084,)
Test : (13474, 9, 9, 65) (13474,)
AlexNet Train/Test: (40419, 9, 9, 65) (40419,) (13474, 9, 9, 65) (13474,)

# 4.0 — Model Definitions

Defines three single-head architectures: AlexNet-based CNN, Global Filter Network (GFNet), and Vision Transformer (ViT with U-Net style skip connections). Custom Keras layers are registered for serialisation compatibility.

## 4.1 — Shared Custom Keras Layers

Reusable layers shared across GFNet and ViT: patch extraction, positional encoding, and the frequency-domain global filter.

In [11]:
@tf.keras.utils.register_keras_serializable()
class PatchExtractor(layers.Layer):
    """Extracts non-overlapping patches from an image tensor."""

    def __init__(self, patch_size=3, **kwargs):
        super().__init__(**kwargs)
        self.patch_size = patch_size

    def call(self, images):
        patches = tf.image.extract_patches(
            images=images,
            sizes=[1, self.patch_size, self.patch_size, 1],
            strides=[1, self.patch_size, self.patch_size, 1],
            rates=[1, 1, 1, 1],
            padding='VALID',
        )
        batch      = tf.shape(images)[0]
        num_patches = tf.shape(patches)[1] * tf.shape(patches)[2]
        patch_dim  = tf.shape(patches)[-1]
        return tf.reshape(patches, [batch, num_patches, patch_dim])

    def get_config(self):
        cfg = super().get_config()
        cfg.update({'patch_size': self.patch_size})
        return cfg


@tf.keras.utils.register_keras_serializable()
class PatchPositionEncoder(layers.Layer):
    """Projects patches to a hidden dim and adds learned positional embeddings (no CLS token)."""

    def __init__(self, num_patches, projection_dim, **kwargs):
        super().__init__(**kwargs)
        self.num_patches    = num_patches
        self.projection_dim = projection_dim
        self.projection         = layers.Dense(projection_dim)
        self.position_embedding = layers.Embedding(input_dim=num_patches, output_dim=projection_dim)

    def call(self, patches):
        positions = tf.range(start=0, limit=self.num_patches, delta=1)
        return self.projection(patches) + self.position_embedding(positions)

    def get_config(self):
        cfg = super().get_config()
        cfg.update({'num_patches': self.num_patches, 'projection_dim': self.projection_dim})
        return cfg


@tf.keras.utils.register_keras_serializable()
class GlobalFilterLayer(layers.Layer):
    """Applies a learnable complex-valued frequency filter via 2-D FFT (GFNet core block)."""

    def __init__(self, token_side, **kwargs):
        super().__init__(**kwargs)
        self.token_side = token_side

    def build(self, input_shape):
        channels = int(input_shape[-1])
        self.w_real = self.add_weight(
            name='w_real', shape=(self.token_side, self.token_side, channels),
            initializer='glorot_uniform', trainable=True,
        )
        self.w_imag = self.add_weight(
            name='w_imag', shape=(self.token_side, self.token_side, channels),
            initializer='zeros', trainable=True,
        )
        super().build(input_shape)

    def call(self, x):
        batch    = tf.shape(x)[0]
        channels = tf.shape(x)[-1]
        x_2d     = tf.reshape(x, [batch, self.token_side, self.token_side, channels])
        x_fft      = tf.signal.fft2d(tf.cast(x_2d, tf.complex64))
        w_complex  = tf.complex(self.w_real, self.w_imag)
        x_filtered = x_fft * w_complex
        x_spatial  = tf.math.real(tf.signal.ifft2d(x_filtered))
        return tf.reshape(x_spatial, [batch, self.token_side * self.token_side, channels])

    def get_config(self):
        cfg = super().get_config()
        cfg.update({'token_side': self.token_side})
        return cfg


@tf.keras.utils.register_keras_serializable()
class PatchEncoderWithCLS(layers.Layer):
    """Projects patches to a hidden dim and prepends a trainable CLS token with positional embeddings."""

    def __init__(self, num_patches, projection_dim, **kwargs):
        super().__init__(**kwargs)
        self.num_patches    = num_patches
        self.projection_dim = projection_dim
        self.projection         = layers.Dense(projection_dim)
        self.position_embedding = layers.Embedding(input_dim=num_patches + 1, output_dim=projection_dim)

    def build(self, input_shape):
        self.cls_token = self.add_weight(
            name='cls_token', shape=(1, 1, self.projection_dim),
            initializer='zeros', trainable=True,
        )
        super().build(input_shape)

    def call(self, patches):
        batch      = tf.shape(patches)[0]
        patch_proj = self.projection(patches)
        cls_tokens = tf.repeat(self.cls_token, repeats=batch, axis=0)
        x          = tf.concat([cls_tokens, patch_proj], axis=1)
        positions  = tf.range(start=0, limit=self.num_patches + 1, delta=1)
        return x + self.position_embedding(positions)

    def get_config(self):
        cfg = super().get_config()
        cfg.update({'num_patches': self.num_patches, 'projection_dim': self.projection_dim})
        return cfg

## 4.2 — AlexNet-Based CNN (Single-Head, Legacy Architecture)

In [12]:
def build_alexnet(input_shape, num_classes, dropout_rate=0.25, cfg=None):
    """Build a legacy AlexNet-style CNN with configurable conv and dense layer sizes."""
    cfg = cfg or ALEXNET_CFG

    inputs = keras.Input(shape=input_shape)
    x = inputs

    for i, filters in enumerate(cfg['conv_filters'], start=1):
        x = layers.Conv2D(filters, (3, 3), activation='relu', padding='same', name=f'alex_conv_{i}')(x)

    x = layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2), padding='same', name='alex_pool')(x)

    dense_units = cfg['dense_units']
    x = layers.Flatten(name='alex_flatten')(x)
    x = layers.Dense(dense_units[0], activation='relu', name='alex_fc1')(x)
    x = layers.Dropout(dropout_rate, name='TRAIN_DROPOUT_1')(x)
    x = layers.Dense(dense_units[1], activation='relu', name='alex_fc2')(x)
    x = layers.Dropout(dropout_rate, name='TRAIN_DROPOUT_2')(x)
    x = layers.Dense(dense_units[2], activation='relu', name='alex_fc3')(x)
    x = layers.Dropout(dropout_rate, name='TRAIN_DROPOUT_3')(x)
    x = layers.Dense(dense_units[3], activation='relu', name='alex_fc4')(x)

    outputs = layers.Dense(num_classes, activation='softmax', name='alex_logits')(x)
    return keras.Model(inputs, outputs, name='AlexNet_SingleHead')

## 4.3 — Global Filter Network (Single-Head, Legacy Architecture)

In [13]:
def gf_block(x, token_side, dim, mlp_ratio=4, dropout_rate=0.25, name_prefix='gf'):
    """Single GFNet block: global filter in frequency domain followed by a gated MLP, with residual."""
    y = layers.LayerNormalization(name=f'{name_prefix}_ln1')(x)
    y = GlobalFilterLayer(token_side, name=f'{name_prefix}_gfilter')(y)
    y = layers.LayerNormalization(name=f'{name_prefix}_ln2')(y)
    y = layers.Dense(dim * mlp_ratio, activation=tf.keras.activations.gelu, name=f'{name_prefix}_mlp1')(y)
    y = layers.Dropout(dropout_rate, name=f'{name_prefix}_drop1')(y)
    y = layers.Dense(dim, activation=tf.keras.activations.gelu, name=f'{name_prefix}_mlp2')(y)
    y = layers.Dropout(dropout_rate, name=f'{name_prefix}_drop2')(y)
    return layers.Add(name=f'{name_prefix}_add')([x, y])


def build_gfnet(input_shape, num_classes, inner_patch=3,
                hidden_dim=512, num_blocks=5, mlp_ratio=4, dropout_rate=0.25):
    """Build a Global Filter Network with configurable depth and width."""
    num_patches = (input_shape[0] // inner_patch) * (input_shape[1] // inner_patch)
    token_side  = int(np.sqrt(num_patches))

    inputs = keras.Input(shape=input_shape)
    x = PatchExtractor(inner_patch, name='gf_patch_extractor')(inputs)
    x = PatchPositionEncoder(num_patches, hidden_dim, name='gf_patch_encoder')(x)
    x = layers.Dropout(dropout_rate, name='TRAIN_DROPOUT_1')(x)

    for i in range(num_blocks):
        x = gf_block(x, token_side, hidden_dim, mlp_ratio, dropout_rate,
                     name_prefix=f'gf_block_{i+1}')

    x = layers.Dropout(dropout_rate, name='TRAIN_DROPOUT_2')(x)
    x = layers.LayerNormalization(name='gf_final_ln')(x)
    x = layers.GlobalAveragePooling1D(name='gf_gap')(x)
    x = layers.Flatten(name='gf_flatten')(x)
    x = layers.Dropout(dropout_rate, name='TRAIN_DROPOUT_3')(x)
    outputs = layers.Dense(num_classes, activation='softmax', name='gf_logits')(x)

    return keras.Model(inputs, outputs, name='GFNet_SingleHead')

## 4.4 — Vision Transformer with U-Net Skip Connections (Single-Head)

In [14]:
def transformer_block(x, num_heads, projection_dim, mlp_dim, dropout_rate, name_prefix):
    """Standard transformer block: MHSA + FFN, each with pre-LN and residual connection."""
    y = layers.LayerNormalization(epsilon=1e-6, name=f'{name_prefix}_ln1')(x)
    y = layers.MultiHeadAttention(
        num_heads=num_heads, key_dim=projection_dim,
        dropout=dropout_rate, name=f'{name_prefix}_mha',
    )(y, y)
    x = layers.Add(name=f'{name_prefix}_add1')([y, x])

    y = layers.LayerNormalization(epsilon=1e-6, name=f'{name_prefix}_ln2')(x)
    y = layers.Dense(mlp_dim, activation=tf.keras.activations.gelu, name=f'{name_prefix}_mlp1')(y)
    y = layers.Dropout(dropout_rate, name=f'{name_prefix}_drop1')(y)
    y = layers.Dense(projection_dim, activation=tf.keras.activations.gelu, name=f'{name_prefix}_mlp2')(y)
    y = layers.Dropout(dropout_rate, name=f'{name_prefix}_drop2')(y)
    return layers.Add(name=f'{name_prefix}_add2')([y, x])


def build_vit_unet_singlehead(
    input_shape, num_classes, inner_patch=3,
    projection_dim=256, num_heads=4, transformer_layers=12,
    mlp_multiplier=2, dropout_rate=0.25, head_units=(512, 256, 128, 64),
):
    """Build a ViT with U-Net-style symmetric skip connections between encoder and decoder blocks."""
    num_patches = (input_shape[0] // inner_patch) * (input_shape[1] // inner_patch)

    inputs = keras.Input(shape=input_shape)
    x = PatchExtractor(inner_patch, name='vit_patch_extractor')(inputs)
    x = PatchEncoderWithCLS(num_patches, projection_dim, name='vit_patch_encoder')(x)

    block_list = []
    for i in range(transformer_layers):
        x = transformer_block(
            x, num_heads=num_heads, projection_dim=projection_dim,
            mlp_dim=projection_dim * mlp_multiplier, dropout_rate=0.1,
            name_prefix=f'vit_block_{i+1}',
        )
        # Save encoder-side outputs for skip connections
        if i <= transformer_layers // 2:
            block_list.append(x)
        else:
            x = layers.Add(name=f'vit_skip_add_{i+1}')([x, block_list[transformer_layers - i - 1]])

    x = layers.Dropout(dropout_rate, name='TRAIN_DROPOUT_1')(x)
    x = layers.LayerNormalization(epsilon=1e-6, name='vit_cls_norm')(x)
    cls_token = layers.Lambda(lambda t: t[:, 0, :], name='vit_cls_token')(x)

    y = layers.Dense(head_units[0], activation=tf.keras.activations.gelu, name='vit_head_1')(cls_token)
    y = layers.Dropout(dropout_rate, name='TRAIN_DROPOUT_3')(y)
    y = layers.Dense(head_units[1], activation=tf.keras.activations.gelu, name='vit_head_2')(y)
    y = layers.Dense(head_units[2], activation=tf.keras.activations.gelu, name='vit_head_3')(y)
    y = layers.Dropout(dropout_rate, name='TRAIN_DROPOUT_5')(y)
    y = layers.Dense(head_units[3], activation=tf.keras.activations.gelu, name='vit_head_4')(y)
    y = layers.Dropout(dropout_rate, name='TRAIN_DROPOUT_6')(y)

    outputs = layers.Dense(num_classes, activation='softmax', name='vit_logits')(y)
    return keras.Model(inputs, outputs, name='ViT_UNet_SingleHead')

# 5.0 — Training & Evaluation Helpers

Utility functions for calibration metrics (Brier score, ECE), the shared AdamW/cosine-decay optimiser factory, and the AlexNet legacy cosine LR scheduler.

In [15]:
def multiclass_brier_score(y_onehot, y_prob):
    """Compute the multiclass Brier score (mean squared error over probability vectors)."""
    return float(np.mean(np.sum((y_prob - y_onehot) ** 2, axis=1)))


def expected_calibration_error(y_true, y_prob, n_bins=15):
    """Compute Expected Calibration Error (ECE) using equal-width confidence bins."""
    confidences = np.max(y_prob, axis=1)
    predictions = np.argmax(y_prob, axis=1)
    correct     = (predictions == y_true).astype(np.float32)

    bin_edges = np.linspace(0.0, 1.0, n_bins + 1)
    ece = 0.0
    for i in range(n_bins):
        lo, hi = bin_edges[i], bin_edges[i + 1]
        in_bin = (confidences >= lo) & (confidences <= hi if i == n_bins - 1 else confidences < hi)
        prop = np.mean(in_bin)
        if prop > 0:
            acc_bin  = np.mean(correct[in_bin])
            conf_bin = np.mean(confidences[in_bin])
            ece     += np.abs(acc_bin - conf_bin) * prop
    return float(ece)


def make_optimizer(num_train_samples):
    """Create an AdamW optimiser with cosine-decay learning rate schedule."""
    steps_per_epoch = int(np.ceil(num_train_samples / BATCH_SIZE))
    decay_steps     = max(1, steps_per_epoch * EPOCHS)
    lr_schedule = keras.optimizers.schedules.CosineDecay(
        initial_learning_rate=LEARNING_RATE,
        decay_steps=decay_steps,
        alpha=TRAIN_CFG['cosine_alpha'],
    )
    return keras.optimizers.AdamW(
        learning_rate=lr_schedule,
        weight_decay=TRAIN_CFG['weight_decay'],
        clipnorm=TRAIN_CFG['clipnorm'],
    )


def _alexnet_legacy_lr(epoch):
    """Cosine LR schedule between ALEXNET_LR_MIN and ALEXNET_LR_MAX (AlexNet legacy recipe)."""
    if EPOCHS <= 1:
        return ALEXNET_LR_START
    phase = np.pi * epoch / (EPOCHS - 1)
    cosine_decay = 0.5 * (1.0 + np.cos(phase))
    return float((ALEXNET_LR_MAX - ALEXNET_LR_MIN) * cosine_decay + ALEXNET_LR_MIN)

# 6.0 — Ensemble Training (M=5)

Trains M=5 independently seeded copies of each selected architecture. Models are first saved locally to avoid Drive I/O crashes mid-run, then copied to Google Drive. Evaluation metrics are collected per ensemble member.

## 6.1 — Builder Wrappers & Directory Setup

In [16]:
import shutil

def build_gfnet_with_cfg(cfg):
    """Instantiate GFNet from a config dict."""
    return build_gfnet(
        input_shape, num_classes, inner_patch=INNER_PATCH,
        hidden_dim=cfg['hidden_dim'], num_blocks=cfg['num_blocks'],
        mlp_ratio=cfg['mlp_ratio'], dropout_rate=DROPOUT_RATE,
    )


def build_vit_with_cfg(cfg):
    """Instantiate ViT-UNet from a config dict."""
    return build_vit_unet_singlehead(
        input_shape, num_classes, inner_patch=INNER_PATCH,
        projection_dim=cfg['projection_dim'], num_heads=cfg['num_heads'],
        transformer_layers=cfg['transformer_layers'], mlp_multiplier=cfg['mlp_multiplier'],
        dropout_rate=DROPOUT_RATE, head_units=tuple(cfg['head_units']),
    )


model_builders = {
    'AlexNet_CNN': lambda: build_alexnet(input_shape, num_classes,
                                         dropout_rate=DROPOUT_RATE, cfg=ALEXNET_CFG),
    'GFNet':       lambda: build_gfnet_with_cfg(GFNET_CFG),
    'ViT_UNet':    lambda: build_vit_with_cfg(VIT_CFG),
}

# Destination directory for ensemble models (lean saving: direct to target destination)
ensemble_dir = MODEL_DIR / 'ensembles'
ensemble_dir.mkdir(parents=True, exist_ok=True)

## 6.2 — Ensemble Training Loop

Iterates over selected architectures, training M=5 members each with a distinct seed. Uses fallback configs when a ResourceExhaustedError is raised. All weights are saved locally first, then synced to Drive.

In [17]:
M = 5

results_rows    = []
model_artifacts = {}

for model_name, builder in model_builders.items():
    print(f"\n{'='*70}\n  Training Ensemble: {model_name} (M={M})\n{'='*70}")
    for i in range(1, M + 1):
        print(f"\n--- {model_name} | Member {i}/{M} (seed={42+i}) ---")
        seed_val = 42 + i
        tf.random.set_seed(seed_val)
        np.random.seed(seed_val)
        random.seed(seed_val)
        tf.keras.backend.clear_session()
        gc.collect()

        # Build model
        capacity_tag = CAPACITY_PRESET
        try:
            model = builder()
        except tf.errors.ResourceExhaustedError:
            print(f"WARNING: Primary config failed with OOM. Falling back...")
            tf.keras.backend.clear_session()
            gc.collect()
            if model_name == 'GFNet':
                model = build_gfnet_with_cfg(GFNET_FALLBACK_CFG)
                capacity_tag = 'fallback_gfnet'
            elif model_name == 'ViT_UNet':
                model = build_vit_with_cfg(VIT_FALLBACK_CFG)
                capacity_tag = 'fallback_vit'
            else:
                raise

        # Direct save path for final ensemble member model (.keras format only)
        final_path = ensemble_dir / f'{model_name}_ens_{i}_final.keras'

        # Configure architecture-specific training
        if model_name == 'AlexNet_CNN':
            alex_lr_schedule = keras.callbacks.LearningRateScheduler(_alexnet_legacy_lr)
            model.compile(
                optimizer=keras.optimizers.Adagrad(learning_rate=ALEXNET_LR_START),
                loss='sparse_categorical_crossentropy',
                metrics=['accuracy'],
            )
            callbacks = [alex_lr_schedule]
            x_tr, y_tr                                         = x_train_alex, y_train_alex
            x_va, y_va                                         = x_test_alex,  y_test_alex
            x_te, y_te, y_te_cat                               = x_test_alex,  y_test_alex, y_test_alex_cat
            x_eval_for_metrics, y_eval_for_metrics, y_eval_for_metrics_cat = (
                x_test_alex, y_test_alex, y_test_alex_cat
            )
            fit_shuffle = False

        else:
            model.compile(
                optimizer=make_optimizer(len(x_train)),
                loss=keras.losses.CategoricalCrossentropy(label_smoothing=TRAIN_CFG['label_smoothing']),
                metrics=['accuracy'],
            )
            callbacks = []
            x_tr, y_tr                                         = x_train, y_train_cat
            x_va, y_va                                         = x_val,   y_val_cat
            x_te, y_te, y_te_cat                               = x_test,  y_test, y_test_cat
            x_eval_for_metrics, y_eval_for_metrics, y_eval_for_metrics_cat = (
                x_val, y_val, y_val_cat
            )
            fit_shuffle = True

        # Train
        train_start = time.perf_counter()
        history_obj = model.fit(
            x_tr, y_tr,
            validation_data=(x_va, y_va),
            epochs=EPOCHS, batch_size=BATCH_SIZE,
            callbacks=callbacks, verbose=1, shuffle=fit_shuffle,
        )
        train_time_sec = float(time.perf_counter() - train_start)

        # Save single full .keras model directly to ensemble destination
        model.save(final_path)
        print(f"Saved ensemble member model: {final_path}")

        # Mirror member 1 to MODEL_DIR for downstream visualization and baseline compatibility
        if i == 1:
            shutil.copy(final_path, MODEL_DIR / f'{model_name}_best.keras')
            shutil.copy(final_path, MODEL_DIR / f'{model_name}_final.keras')

        # Evaluate
        y_eval_prob = model.predict(x_eval_for_metrics, batch_size=BATCH_SIZE, verbose=0)
        y_test_prob = model.predict(x_te,               batch_size=BATCH_SIZE, verbose=0)
        y_eval_pred = np.argmax(y_eval_prob, axis=1)
        y_test_pred = np.argmax(y_test_prob, axis=1)

        report = classification_report(y_te, y_test_pred, output_dict=True, zero_division=0)
        cm      = confusion_matrix(y_te, y_test_pred)

        row = {
            'model':              f'{model_name}_ens_{i}',
            'capacity_tag':       capacity_tag,
            'test_accuracy':      float(accuracy_score(y_te, y_test_pred)),
            'kappa':              float(cohen_kappa_score(y_te, y_test_pred)),
            'macro_f1':           float(f1_score(y_te, y_test_pred, average='macro')),
            'weighted_f1':        float(f1_score(y_te, y_test_pred, average='weighted')),
            'val_nll':            float(log_loss(y_eval_for_metrics, y_eval_prob, labels=np.arange(num_classes))),
            'test_nll':           float(log_loss(y_te, y_test_prob, labels=np.arange(num_classes))),
            'val_brier':          multiclass_brier_score(y_eval_for_metrics_cat, y_eval_prob),
            'test_brier':         multiclass_brier_score(y_te_cat, y_test_prob),
            'test_ece_15bin':     expected_calibration_error(y_te, y_test_prob, n_bins=15),
            'epochs_configured':  int(EPOCHS),
            'epochs_ran':         int(len(history_obj.history.get('loss', []))),
            'train_time_sec':     train_time_sec,
            'best_model_path':    str(MODEL_DIR / f'{model_name}_best.keras') if (i == 1) else str(final_path),
            'final_model_path':   str(final_path),
        }
        results_rows.append(row)

        # Store last member's artifacts for plotting
        if i == M:
            model_artifacts[model_name] = {
                'report':           report,
                'confusion_matrix': cm,
                'history':          history_obj.history,
            }

        # Clear session and collect garbage to prevent VRAM accumulation
        del model
        tf.keras.backend.clear_session()
        gc.collect()

summary_df = (pd.DataFrame(results_rows)
                .sort_values('test_accuracy', ascending=False)
                .reset_index(drop=True))
summary_df

======================================================================
  Training Ensemble: AlexNet_CNN (M=5)
======================================================================

--- AlexNet_CNN | Member 1/5 (seed=43) ---

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1789195202.973006      23 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 15511 MB memory:  -> device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0

Epoch 1/100
  5/316 ━━━━━━━━━━━━━━━━━━━━ 9s 31ms/step - accuracy: 0.1786 - loss: 2.0474

I0000 00:00:1789195214.928855      71 device_compiler.h:196] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

316/316 ━━━━━━━━━━━━━━━━━━━━ 28s 61ms/step - accuracy: 0.3580 - loss: 1.6130 - val_accuracy: 0.5206 - val_loss: 1.0486 - learning_rate: 0.0200
Epoch 2/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.3882 - loss: 1.6505 - val_accuracy: 0.4476 - val_loss: 1.4398 - learning_rate: 0.0200
Epoch 3/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.5120 - loss: 1.1920 - val_accuracy: 0.5193 - val_loss: 1.1089 - learning_rate: 0.0200
Epoch 4/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.4992 - loss: 1.5065 - val_accuracy: 0.5868 - val_loss: 0.9791 - learning_rate: 0.0200
Epoch 5/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.6371 - loss: 0.9037 - val_accuracy: 0.7428 - val_loss: 0.6733 - learning_rate: 0.0199
Epoch 6/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.6552 - loss: 0.9216 - val_accuracy: 0.7680 - val_loss: 0.6553 - learning_rate: 0.0199
Epoch 7/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.7455 - loss: 0.6578 - val_accuracy: 0.6730 - val_loss: 0.8564 - learning_rate: 0.0199
Epoch 8/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.7780 - loss: 0.5828 - val_accuracy: 0.8432 - val_loss: 0.4617 - learning_rate: 0.0198
Epoch 9/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.8016 - loss: 0.5323 - val_accuracy: 0.8455 - val_loss: 0.4260 - learning_rate: 0.0198
Epoch 10/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.8204 - loss: 0.4883 - val_accuracy: 0.8303 - val_loss: 0.4766 - learning_rate: 0.0197
Epoch 11/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.8282 - loss: 0.4636 - val_accuracy: 0.7633 - val_loss: 0.6248 - learning_rate: 0.0196
Epoch 12/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.8422 - loss: 0.4265 - val_accuracy: 0.8283 - val_loss: 0.4404 - learning_rate: 0.0195
Epoch 13/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.8513 - loss: 0.4025 - val_accuracy: 0.8190 - val_loss: 0.4834 - learning_rate: 0.0195
Epoch 14/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.8567 - loss: 0.3817 - val_accuracy: 0.7930 - val_loss: 0.5981 - learning_rate: 0.0194
Epoch 15/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.7411 - loss: 0.7625 - val_accuracy: 0.7935 - val_loss: 0.5336 - learning_rate: 0.0193
Epoch 16/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.8481 - loss: 0.4348 - val_accuracy: 0.8861 - val_loss: 0.3469 - learning_rate: 0.0192
Epoch 17/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.8693 - loss: 0.3678 - val_accuracy: 0.8821 - val_loss: 0.3511 - learning_rate: 0.0191
Epoch 18/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.8757 - loss: 0.3390 - val_accuracy: 0.8313 - val_loss: 0.5291 - learning_rate: 0.0189
Epoch 19/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.8844 - loss: 0.3134 - val_accuracy: 0.8381 - val_loss: 0.4896 - learning_rate: 0.0188
Epoch 20/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.8880 - loss: 0.2982 - val_accuracy: 0.8637 - val_loss: 0.3502 - learning_rate: 0.0187
Epoch 21/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.8967 - loss: 0.2736 - val_accuracy: 0.8533 - val_loss: 0.4254 - learning_rate: 0.0185
Epoch 22/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9008 - loss: 0.2670 - val_accuracy: 0.8807 - val_loss: 0.3061 - learning_rate: 0.0184
Epoch 23/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9083 - loss: 0.2400 - val_accuracy: 0.9207 - val_loss: 0.2041 - learning_rate: 0.0182
Epoch 24/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.8915 - loss: 0.2980 - val_accuracy: 0.9042 - val_loss: 0.2401 - learning_rate: 0.0181
Epoch 25/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9086 - loss: 0.2407 - val_accuracy: 0.9403 - val_loss: 0.1629 - learning_rate: 0.0179
Epoch 26/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9211 - loss: 0.2085 - val_accuracy: 0.9266 - val_loss: 0.1784 - learning_rate: 0.0178
Epoch 27/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9256 - loss: 0.1966 - val_accuracy: 0.9449 - val_loss: 0.1450 - learning_rate: 0.0176
Epoch 28/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9333 - loss: 0.1863 - val_accuracy: 0.9420 - val_loss: 0.1500 - learning_rate: 0.0174
Epoch 29/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9372 - loss: 0.1680 - val_accuracy: 0.9345 - val_loss: 0.1630 - learning_rate: 0.0172
Epoch 30/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9428 - loss: 0.1583 - val_accuracy: 0.9369 - val_loss: 0.1702 - learning_rate: 0.0170
Epoch 31/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9500 - loss: 0.1422 - val_accuracy: 0.9586 - val_loss: 0.1076 - learning_rate: 0.0169
Epoch 32/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9412 - loss: 0.1695 - val_accuracy: 0.9577 - val_loss: 0.1180 - learning_rate: 0.0167
Epoch 33/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9541 - loss: 0.1338 - val_accuracy: 0.9636 - val_loss: 0.0956 - learning_rate: 0.0165
Epoch 34/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9587 - loss: 0.1177 - val_accuracy: 0.9636 - val_loss: 0.0951 - learning_rate: 0.0162
Epoch 35/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9589 - loss: 0.1244 - val_accuracy: 0.9693 - val_loss: 0.0849 - learning_rate: 0.0160
Epoch 36/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9639 - loss: 0.1067 - val_accuracy: 0.9752 - val_loss: 0.0705 - learning_rate: 0.0158
Epoch 37/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9662 - loss: 0.0986 - val_accuracy: 0.9780 - val_loss: 0.0643 - learning_rate: 0.0156
Epoch 38/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9690 - loss: 0.0915 - val_accuracy: 0.9814 - val_loss: 0.0533 - learning_rate: 0.0154
Epoch 39/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9717 - loss: 0.0846 - val_accuracy: 0.9834 - val_loss: 0.0492 - learning_rate: 0.0152
Epoch 40/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9753 - loss: 0.0735 - val_accuracy: 0.9751 - val_loss: 0.0680 - learning_rate: 0.0150
Epoch 41/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9773 - loss: 0.0698 - val_accuracy: 0.9863 - val_loss: 0.0412 - learning_rate: 0.0147
Epoch 42/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9783 - loss: 0.0669 - val_accuracy: 0.9765 - val_loss: 0.0637 - learning_rate: 0.0145
Epoch 43/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9804 - loss: 0.0624 - val_accuracy: 0.9875 - val_loss: 0.0405 - learning_rate: 0.0143
Epoch 44/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9843 - loss: 0.0486 - val_accuracy: 0.9892 - val_loss: 0.0325 - learning_rate: 0.0140
Epoch 45/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9838 - loss: 0.0529 - val_accuracy: 0.9898 - val_loss: 0.0337 - learning_rate: 0.0138
Epoch 46/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9854 - loss: 0.0454 - val_accuracy: 0.9914 - val_loss: 0.0263 - learning_rate: 0.0136
Epoch 47/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9839 - loss: 0.0529 - val_accuracy: 0.9880 - val_loss: 0.0384 - learning_rate: 0.0133
Epoch 48/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9869 - loss: 0.0409 - val_accuracy: 0.9921 - val_loss: 0.0264 - learning_rate: 0.0131
Epoch 49/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9897 - loss: 0.0327 - val_accuracy: 0.9939 - val_loss: 0.0222 - learning_rate: 0.0129
Epoch 50/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9902 - loss: 0.0313 - val_accuracy: 0.9937 - val_loss: 0.0210 - learning_rate: 0.0126
Epoch 51/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9900 - loss: 0.0331 - val_accuracy: 0.9914 - val_loss: 0.0257 - learning_rate: 0.0124
Epoch 52/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9898 - loss: 0.0329 - val_accuracy: 0.9932 - val_loss: 0.0214 - learning_rate: 0.0121
Epoch 53/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9918 - loss: 0.0273 - val_accuracy: 0.9941 - val_loss: 0.0187 - learning_rate: 0.0119
Epoch 54/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9930 - loss: 0.0225 - val_accuracy: 0.9947 - val_loss: 0.0171 - learning_rate: 0.0117
Epoch 55/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9935 - loss: 0.0221 - val_accuracy: 0.9921 - val_loss: 0.0306 - learning_rate: 0.0114
Epoch 56/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9907 - loss: 0.0315 - val_accuracy: 0.9955 - val_loss: 0.0154 - learning_rate: 0.0112
Epoch 57/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9947 - loss: 0.0173 - val_accuracy: 0.9958 - val_loss: 0.0143 - learning_rate: 0.0110
Epoch 58/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9945 - loss: 0.0204 - val_accuracy: 0.9949 - val_loss: 0.0177 - learning_rate: 0.0107
Epoch 59/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9948 - loss: 0.0180 - val_accuracy: 0.9965 - val_loss: 0.0120 - learning_rate: 0.0105
Epoch 60/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9955 - loss: 0.0147 - val_accuracy: 0.9964 - val_loss: 0.0128 - learning_rate: 0.0103
Epoch 61/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9957 - loss: 0.0139 - val_accuracy: 0.9961 - val_loss: 0.0148 - learning_rate: 0.0100
Epoch 62/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9946 - loss: 0.0207 - val_accuracy: 0.9968 - val_loss: 0.0107 - learning_rate: 0.0098
Epoch 63/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9967 - loss: 0.0109 - val_accuracy: 0.9971 - val_loss: 0.0101 - learning_rate: 0.0096
Epoch 64/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9968 - loss: 0.0107 - val_accuracy: 0.9971 - val_loss: 0.0102 - learning_rate: 0.0094
Epoch 65/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9970 - loss: 0.0101 - val_accuracy: 0.9967 - val_loss: 0.0101 - learning_rate: 0.0092
Epoch 66/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9962 - loss: 0.0134 - val_accuracy: 0.9958 - val_loss: 0.0123 - learning_rate: 0.0090
Epoch 67/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9974 - loss: 0.0093 - val_accuracy: 0.9973 - val_loss: 0.0099 - learning_rate: 0.0088
Epoch 68/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9973 - loss: 0.0092 - val_accuracy: 0.9975 - val_loss: 0.0098 - learning_rate: 0.0085
Epoch 69/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9982 - loss: 0.0064 - val_accuracy: 0.9975 - val_loss: 0.0080 - learning_rate: 0.0083
Epoch 70/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9983 - loss: 0.0060 - val_accuracy: 0.9979 - val_loss: 0.0069 - learning_rate: 0.0081
Epoch 71/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9981 - loss: 0.0068 - val_accuracy: 0.9979 - val_loss: 0.0070 - learning_rate: 0.0080
Epoch 72/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9981 - loss: 0.0066 - val_accuracy: 0.9980 - val_loss: 0.0070 - learning_rate: 0.0078
Epoch 73/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9978 - loss: 0.0074 - val_accuracy: 0.9980 - val_loss: 0.0083 - learning_rate: 0.0076
Epoch 74/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9984 - loss: 0.0063 - val_accuracy: 0.9986 - val_loss: 0.0060 - learning_rate: 0.0074
Epoch 75/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9982 - loss: 0.0061 - val_accuracy: 0.9977 - val_loss: 0.0087 - learning_rate: 0.0072
Epoch 76/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9985 - loss: 0.0052 - val_accuracy: 0.9983 - val_loss: 0.0061 - learning_rate: 0.0071
Epoch 77/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9986 - loss: 0.0050 - val_accuracy: 0.9970 - val_loss: 0.0101 - learning_rate: 0.0069
Epoch 78/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9990 - loss: 0.0041 - val_accuracy: 0.9985 - val_loss: 0.0057 - learning_rate: 0.0068
Epoch 79/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9987 - loss: 0.0043 - val_accuracy: 0.9979 - val_loss: 0.0069 - learning_rate: 0.0066
Epoch 80/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9988 - loss: 0.0044 - val_accuracy: 0.9987 - val_loss: 0.0057 - learning_rate: 0.0065
Epoch 81/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9990 - loss: 0.0040 - val_accuracy: 0.9987 - val_loss: 0.0054 - learning_rate: 0.0063
Epoch 82/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9992 - loss: 0.0035 - val_accuracy: 0.9985 - val_loss: 0.0062 - learning_rate: 0.0062
Epoch 83/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9992 - loss: 0.0033 - val_accuracy: 0.9985 - val_loss: 0.0057 - learning_rate: 0.0061
Epoch 84/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9996 - loss: 0.0024 - val_accuracy: 0.9987 - val_loss: 0.0050 - learning_rate: 0.0059
Epoch 85/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9993 - loss: 0.0031 - val_accuracy: 0.9988 - val_loss: 0.0054 - learning_rate: 0.0058
Epoch 86/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9992 - loss: 0.0033 - val_accuracy: 0.9978 - val_loss: 0.0080 - learning_rate: 0.0057
Epoch 87/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9992 - loss: 0.0030 - val_accuracy: 0.9990 - val_loss: 0.0046 - learning_rate: 0.0056
Epoch 88/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9990 - loss: 0.0037 - val_accuracy: 0.9982 - val_loss: 0.0075 - learning_rate: 0.0055
Epoch 89/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9994 - loss: 0.0027 - val_accuracy: 0.9987 - val_loss: 0.0058 - learning_rate: 0.0055
Epoch 90/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9993 - loss: 0.0030 - val_accuracy: 0.9983 - val_loss: 0.0060 - learning_rate: 0.0054
Epoch 91/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9996 - loss: 0.0019 - val_accuracy: 0.9990 - val_loss: 0.0044 - learning_rate: 0.0053
Epoch 92/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9993 - loss: 0.0025 - val_accuracy: 0.9993 - val_loss: 0.0039 - learning_rate: 0.0052
Epoch 93/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9993 - loss: 0.0023 - val_accuracy: 0.9987 - val_loss: 0.0047 - learning_rate: 0.0052
Epoch 94/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9995 - loss: 0.0021 - val_accuracy: 0.9988 - val_loss: 0.0048 - learning_rate: 0.0051
Epoch 95/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9995 - loss: 0.0022 - val_accuracy: 0.9984 - val_loss: 0.0059 - learning_rate: 0.0051
Epoch 96/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9994 - loss: 0.0023 - val_accuracy: 0.9990 - val_loss: 0.0050 - learning_rate: 0.0051
Epoch 97/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9996 - loss: 0.0018 - val_accuracy: 0.9990 - val_loss: 0.0042 - learning_rate: 0.0050
Epoch 98/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9994 - loss: 0.0022 - val_accuracy: 0.9990 - val_loss: 0.0054 - learning_rate: 0.0050
Epoch 99/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9994 - loss: 0.0022 - val_accuracy: 0.9968 - val_loss: 0.0126 - learning_rate: 0.0050
Epoch 100/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9994 - loss: 0.0025 - val_accuracy: 0.9990 - val_loss: 0.0048 - learning_rate: 0.0050
Saved ensemble member model: /kaggle/working/results/models/ensembles/AlexNet_CNN_ens_1_final.keras

--- AlexNet_CNN | Member 2/5 (seed=44) ---
Epoch 1/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.3444 - loss: 1.7077 - val_accuracy: 0.5203 - val_loss: 1.2126 - learning_rate: 0.0200
Epoch 2/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.5203 - loss: 1.0774 - val_accuracy: 0.5565 - val_loss: 0.9785 - learning_rate: 0.0200
Epoch 3/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.4998 - loss: 1.2739 - val_accuracy: 0.4144 - val_loss: 1.3478 - learning_rate: 0.0200
Epoch 4/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.4720 - loss: 1.2791 - val_accuracy: 0.5297 - val_loss: 1.0355 - learning_rate: 0.0200
Epoch 5/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.5477 - loss: 1.0174 - val_accuracy: 0.5784 - val_loss: 0.9391 - learning_rate: 0.0199
Epoch 6/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.5802 - loss: 0.9364 - val_accuracy: 0.5777 - val_loss: 0.9413 - learning_rate: 0.0199
Epoch 7/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.6021 - loss: 0.8997 - val_accuracy: 0.5986 - val_loss: 0.9174 - learning_rate: 0.0199
Epoch 8/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.6119 - loss: 0.8796 - val_accuracy: 0.6034 - val_loss: 0.8623 - learning_rate: 0.0198
Epoch 9/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.6237 - loss: 0.8514 - val_accuracy: 0.6210 - val_loss: 0.8112 - learning_rate: 0.0198
Epoch 10/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.6320 - loss: 0.8271 - val_accuracy: 0.6288 - val_loss: 0.7734 - learning_rate: 0.0197
Epoch 11/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.6392 - loss: 0.8071 - val_accuracy: 0.6308 - val_loss: 0.7659 - learning_rate: 0.0196
Epoch 12/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.6515 - loss: 0.7795 - val_accuracy: 0.6047 - val_loss: 0.9159 - learning_rate: 0.0195
Epoch 13/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.6972 - loss: 0.7376 - val_accuracy: 0.7164 - val_loss: 0.7155 - learning_rate: 0.0195
Epoch 14/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.7729 - loss: 0.6094 - val_accuracy: 0.6965 - val_loss: 0.9419 - learning_rate: 0.0194
Epoch 15/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.8094 - loss: 0.5192 - val_accuracy: 0.8557 - val_loss: 0.3803 - learning_rate: 0.0193
Epoch 16/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.8374 - loss: 0.4406 - val_accuracy: 0.8522 - val_loss: 0.3665 - learning_rate: 0.0192
Epoch 17/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.8493 - loss: 0.4077 - val_accuracy: 0.8453 - val_loss: 0.3639 - learning_rate: 0.0191
Epoch 18/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.8627 - loss: 0.3757 - val_accuracy: 0.8453 - val_loss: 0.3992 - learning_rate: 0.0189
Epoch 19/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.8731 - loss: 0.3478 - val_accuracy: 0.8706 - val_loss: 0.3220 - learning_rate: 0.0188
Epoch 20/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.8821 - loss: 0.3201 - val_accuracy: 0.8592 - val_loss: 0.3442 - learning_rate: 0.0187
Epoch 21/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.8906 - loss: 0.3012 - val_accuracy: 0.8957 - val_loss: 0.2629 - learning_rate: 0.0185
Epoch 22/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9011 - loss: 0.2695 - val_accuracy: 0.9158 - val_loss: 0.2426 - learning_rate: 0.0184
Epoch 23/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9119 - loss: 0.2409 - val_accuracy: 0.9339 - val_loss: 0.1799 - learning_rate: 0.0182
Epoch 24/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9195 - loss: 0.2193 - val_accuracy: 0.8819 - val_loss: 0.3154 - learning_rate: 0.0181
Epoch 25/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9254 - loss: 0.2045 - val_accuracy: 0.9300 - val_loss: 0.1864 - learning_rate: 0.0179
Epoch 26/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.9307 - loss: 0.1900 - val_accuracy: 0.9125 - val_loss: 0.2193 - learning_rate: 0.0178
Epoch 27/100
316/316 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9379 - loss: 0.1704 - val_accuracy: 0.9094 - val_loss: 0.2449 - learning_rate: 0.0176
Epoch 28/100

,model,capacity_tag,test_accuracy,kappa,macro_f1,weighted_f1,val_nll,test_nll,val_brier,test_brier,test_ece_15bin,epochs_configured,epochs_ran,train_time_sec,best_model_path,final_model_path
0,GFNet_ens_2,legacy_arch,1.000000,1.000000,1.000000,1.000000,0.008651,0.008395,0.000347,0.000164,0.008325,100,100,1091.392252,/kaggle/working/results/models/ensembles/GFNet...,/kaggle/working/results/models/ensembles/GFNet...
1,GFNet_ens_1,legacy_arch,1.000000,1.000000,1.000000,1.000000,0.007783,0.007580,0.000225,0.000087,0.007543,100,100,1093.302967,/kaggle/working/results/models/GFNet_best.keras,/kaggle/working/results/models/ensembles/GFNet...
2,GFNet_ens_3,legacy_arch,1.000000,1.000000,1.000000,1.000000,0.007836,0.007709,0.000154,0.000092,0.007669,100,100,1095.502845,/kaggle/working/results/models/ensembles/GFNet...,/kaggle/working/results/models/ensembles/GFNet...
3,GFNet_ens_4,legacy_arch,1.000000,1.000000,1.000000,1.000000,0.008376,0.008268,0.000113,0.000088,0.008230,100,100,1098.823249,/kaggle/working/results/models/ensembles/GFNet...,/kaggle/working/results/models/ensembles/GFNet...
4,GFNet_ens_5,legacy_arch,1.000000,1.000000,1.000000,1.000000,0.008145,0.007578,0.000380,0.000086,0.007542,100,100,1096.156632,/kaggle/working/results/models/ensembles/GFNet...,/kaggle/working/results/models/ensembles/GFNet...
5,ViT_UNet_ens_1,legacy_arch,0.999703,0.999642,0.999313,0.999703,0.041252,0.040386,0.002659,0.002209,0.038699,100,100,2127.257506,/kaggle/working/results/models/ViT_UNet_best.k...,/kaggle/working/results/models/ensembles/ViT_U...
6,ViT_UNet_ens_4,legacy_arch,0.999703,0.999642,0.999287,0.999703,0.040882,0.039835,0.002633,0.002131,0.038167,100,100,2151.865034,/kaggle/working/results/models/ensembles/ViT_U...,/kaggle/working/results/models/ensembles/ViT_U...
7,ViT_UNet_ens_5,legacy_arch,0.999629,0.999553,0.999148,0.999629,0.042937,0.040958,0.003405,0.002444,0.038928,100,100,2149.094057,/kaggle/working/results/models/ensembles/ViT_U...,/kaggle/working/results/models/ensembles/ViT_U...
8,ViT_UNet_ens_3,legacy_arch,0.999629,0.999553,0.998978,0.999629,0.041512,0.041094,0.002767,0.002441,0.038689,100,100,2108.280855,/kaggle/working/results/models/ensembles/ViT_U...,/kaggle/working/results/models/ensembles/ViT_U...
9,AlexNet_CNN_ens_3,legacy_arch,0.999480,0.999374,0.998839,0.999480,0.002538,0.002538,0.000778,0.000778,0.000254,100,100,1067.531324,/kaggle/working/results/models/ensembles/AlexN...,/kaggle/working/results/models/ensembles/AlexN...
10,ViT_UNet_ens_2,legacy_arch,0.999406,0.999285,0.998563,0.999406,0.043563,0.041529,0.003853,0.002737,0.038361,100,100,2130.164796,/kaggle/working/results/models/ensembles/ViT_U...,/kaggle/working/results/models/ensembles/ViT_U...
11,AlexNet_CNN_ens_5,legacy_arch,0.999332,0.999195,0.998941,0.999332,0.002242,0.002242,0.001048,0.001048,0.000464,100,100,1071.647641,/kaggle/working/results/models/ensembles/AlexN...,/kaggle/working/results/models/ensembles/AlexN...
12,AlexNet_CNN_ens_1,legacy_arch,0.998961,0.998748,0.998048,0.998960,0.004822,0.004822,0.001877,0.001877,0.000390,100,100,1085.356658,/kaggle/working/results/models/AlexNet_CNN_bes...,/kaggle/working/results/models/ensembles/AlexN...
13,AlexNet_CNN_ens_4,legacy_arch,0.996809,0.996155,0.994774,0.996806,0.011597,0.011597,0.005575,0.005575,0.001241,100,100,1071.631854,/kaggle/working/results/models/ensembles/AlexN...,/kaggle/working/results/models/ensembles/AlexN...
14,AlexNet_CNN_ens_2,legacy_arch,0.996066,0.995261,0.990710,0.996060,0.013131,0.013131,0.006438,0.006438,0.001688,100,100,1069.520384,/kaggle/working/results/models/ensembles/AlexN...,/kaggle/working/results/models/ensembles/AlexN...

# 7.0 — Results & Analysis

Saves the classification summary CSV, plots training curves, cross-model metric comparisons, calibration proxy charts, and per-model confusion matrices.

## 7.1 — Save Summary CSV & Per-Model Reports

In [18]:
summary_path = MODEL_DIR / 'classification_summary.csv'
summary_df.to_csv(summary_path, index=False)
if OUTPUT_ROOT != MODEL_DIR:
    summary_df.to_csv(OUTPUT_ROOT / 'classification_summary.csv', index=False)
print('Saved summary:', summary_path)

for model_name, artifact in model_artifacts.items():
    report_path = MODEL_DIR / f'{model_name}_classification_report.json'
    with open(report_path, 'w', encoding='utf-8') as f:
        json.dump(artifact['report'], f, indent=2)
    if OUTPUT_ROOT != MODEL_DIR:
        with open(OUTPUT_ROOT / f'{model_name}_classification_report.json', 'w', encoding='utf-8') as f:
            json.dump(artifact['report'], f, indent=2)

print('Saved per-model classification reports in:', MODEL_DIR)
summary_df

Saved summary: /kaggle/working/results/models/classification_summary.csv
Saved per-model classification reports in: /kaggle/working/results/models

,model,capacity_tag,test_accuracy,kappa,macro_f1,weighted_f1,val_nll,test_nll,val_brier,test_brier,test_ece_15bin,epochs_configured,epochs_ran,train_time_sec,best_model_path,final_model_path
0,GFNet_ens_2,legacy_arch,1.000000,1.000000,1.000000,1.000000,0.008651,0.008395,0.000347,0.000164,0.008325,100,100,1091.392252,/kaggle/working/results/models/ensembles/GFNet...,/kaggle/working/results/models/ensembles/GFNet...
1,GFNet_ens_1,legacy_arch,1.000000,1.000000,1.000000,1.000000,0.007783,0.007580,0.000225,0.000087,0.007543,100,100,1093.302967,/kaggle/working/results/models/GFNet_best.keras,/kaggle/working/results/models/ensembles/GFNet...
2,GFNet_ens_3,legacy_arch,1.000000,1.000000,1.000000,1.000000,0.007836,0.007709,0.000154,0.000092,0.007669,100,100,1095.502845,/kaggle/working/results/models/ensembles/GFNet...,/kaggle/working/results/models/ensembles/GFNet...
3,GFNet_ens_4,legacy_arch,1.000000,1.000000,1.000000,1.000000,0.008376,0.008268,0.000113,0.000088,0.008230,100,100,1098.823249,/kaggle/working/results/models/ensembles/GFNet...,/kaggle/working/results/models/ensembles/GFNet...
4,GFNet_ens_5,legacy_arch,1.000000,1.000000,1.000000,1.000000,0.008145,0.007578,0.000380,0.000086,0.007542,100,100,1096.156632,/kaggle/working/results/models/ensembles/GFNet...,/kaggle/working/results/models/ensembles/GFNet...
5,ViT_UNet_ens_1,legacy_arch,0.999703,0.999642,0.999313,0.999703,0.041252,0.040386,0.002659,0.002209,0.038699,100,100,2127.257506,/kaggle/working/results/models/ViT_UNet_best.k...,/kaggle/working/results/models/ensembles/ViT_U...
6,ViT_UNet_ens_4,legacy_arch,0.999703,0.999642,0.999287,0.999703,0.040882,0.039835,0.002633,0.002131,0.038167,100,100,2151.865034,/kaggle/working/results/models/ensembles/ViT_U...,/kaggle/working/results/models/ensembles/ViT_U...
7,ViT_UNet_ens_5,legacy_arch,0.999629,0.999553,0.999148,0.999629,0.042937,0.040958,0.003405,0.002444,0.038928,100,100,2149.094057,/kaggle/working/results/models/ensembles/ViT_U...,/kaggle/working/results/models/ensembles/ViT_U...
8,ViT_UNet_ens_3,legacy_arch,0.999629,0.999553,0.998978,0.999629,0.041512,0.041094,0.002767,0.002441,0.038689,100,100,2108.280855,/kaggle/working/results/models/ensembles/ViT_U...,/kaggle/working/results/models/ensembles/ViT_U...
9,AlexNet_CNN_ens_3,legacy_arch,0.999480,0.999374,0.998839,0.999480,0.002538,0.002538,0.000778,0.000778,0.000254,100,100,1067.531324,/kaggle/working/results/models/ensembles/AlexN...,/kaggle/working/results/models/ensembles/AlexN...
10,ViT_UNet_ens_2,legacy_arch,0.999406,0.999285,0.998563,0.999406,0.043563,0.041529,0.003853,0.002737,0.038361,100,100,2130.164796,/kaggle/working/results/models/ensembles/ViT_U...,/kaggle/working/results/models/ensembles/ViT_U...
11,AlexNet_CNN_ens_5,legacy_arch,0.999332,0.999195,0.998941,0.999332,0.002242,0.002242,0.001048,0.001048,0.000464,100,100,1071.647641,/kaggle/working/results/models/ensembles/AlexN...,/kaggle/working/results/models/ensembles/AlexN...
12,AlexNet_CNN_ens_1,legacy_arch,0.998961,0.998748,0.998048,0.998960,0.004822,0.004822,0.001877,0.001877,0.000390,100,100,1085.356658,/kaggle/working/results/models/AlexNet_CNN_bes...,/kaggle/working/results/models/ensembles/AlexN...
13,AlexNet_CNN_ens_4,legacy_arch,0.996809,0.996155,0.994774,0.996806,0.011597,0.011597,0.005575,0.005575,0.001241,100,100,1071.631854,/kaggle/working/results/models/ensembles/AlexN...,/kaggle/working/results/models/ensembles/AlexN...
14,AlexNet_CNN_ens_2,legacy_arch,0.996066,0.995261,0.990710,0.996060,0.013131,0.013131,0.006438,0.006438,0.001688,100,100,1069.520384,/kaggle/working/results/models/ensembles/AlexN...,/kaggle/working/results/models/ensembles/AlexN...

## 7.2 — Training Curves (Accuracy & Loss)

Plots dual-axis accuracy/loss curves for each trained model and saves them to `PLOT_DIR`.

In [19]:
for model_name, artifact in model_artifacts.items():
    hist   = artifact['history']
    epochs = np.arange(1, len(hist['loss']) + 1)

    fig, ax1 = plt.subplots(figsize=(12, 5))
    ax1.plot(epochs, hist['accuracy'],     color='#1f77b4', linewidth=2, label='Train Accuracy')
    ax1.plot(epochs, hist['val_accuracy'], color='#2ca02c', linewidth=2, linestyle='--', label='Val Accuracy')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Accuracy')
    ax1.set_ylim(0, 1.0)
    ax1.grid(True, alpha=0.25)

    ax2 = ax1.twinx()
    ax2.plot(epochs, hist['loss'],     color='#111111', linewidth=1.8, label='Train Loss')
    ax2.plot(epochs, hist['val_loss'], color='#d62728', linewidth=1.8, linestyle='--', label='Val Loss')
    ax2.set_ylabel('Loss')

    lines  = ax1.get_lines() + ax2.get_lines()
    labels = [ln.get_label() for ln in lines]
    ax1.legend(lines, labels, loc='upper right', frameon=True)
    plt.title(f'{model_name}: Accuracy/Loss vs Epoch')
    plt.tight_layout()

    curve_path = PLOT_DIR / f'{model_name}_training_curves.png'
    plt.savefig(curve_path, dpi=200, bbox_inches='tight')
    if OUTPUT_ROOT != PLOT_DIR:
        plt.savefig(OUTPUT_ROOT / f'{model_name}_training_curves.png', dpi=200, bbox_inches='tight')
    plt.show()
    plt.close(fig)

## 7.3 — Cross-Model Metric Comparison Charts

In [20]:
plot_df = summary_df[[
    'model', 'test_accuracy', 'macro_f1', 'kappa',
    'train_time_sec', 'test_nll', 'test_brier', 'test_ece_15bin',
]].copy()

fig, axes = plt.subplots(2, 2, figsize=(15, 9))
axes    = axes.flatten()

metric_specs = [
    ('test_accuracy',  'Test Accuracy',   (0.0, 1.0), '{:.3f}'),
    ('macro_f1',       'Macro F1',        (0.0, 1.0), '{:.3f}'),
    ('kappa',          'Cohen Kappa',     (0.0, 1.0), '{:.3f}'),
    ('train_time_sec', 'Train Time (sec)', None,       '{:.1f}'),
]

for ax, (col, title, ylim, fmt) in zip(axes, metric_specs):
    local   = plot_df[['model', col]].copy()
    palette = sns.color_palette('tab20', len(local))
    bars    = ax.bar(local['model'], local[col], color=palette)
    ax.set_title(title)
    ax.set_xlabel('Model')
    ax.set_ylabel(title)
    ax.tick_params(axis='x', rotation=45)
    if ylim is not None:
        ax.set_ylim(*ylim)
    ax.grid(axis='y', alpha=0.25)
    for patch in bars:
        height = patch.get_height()
        x      = patch.get_x() + patch.get_width() / 2
        offset = (ylim[1] - ylim[0]) * 0.02 if ylim else max(local[col].max() * 0.02, 0.05)
        ax.text(x, height + offset, fmt.format(height), ha='center', va='bottom', fontsize=8)

plt.suptitle('Single-Head Model Comparison', y=1.02, fontsize=14)
plt.tight_layout()
comparison_path = PLOT_DIR / 'model_comparison_metrics.png'
plt.savefig(comparison_path, dpi=200, bbox_inches='tight')
if OUTPUT_ROOT != PLOT_DIR:
    plt.savefig(OUTPUT_ROOT / 'model_comparison_metrics.png', dpi=200, bbox_inches='tight')
plt.show()
plt.close(fig)

## 7.4 — Calibration Proxy Metrics Chart

In [21]:
fig, ax = plt.subplots(figsize=(14, 5))
calib_cols = ['test_nll', 'test_brier', 'test_ece_15bin']
calib_df   = plot_df[['model'] + calib_cols].set_index('model')
calib_df.plot(kind='bar', ax=ax, rot=45)
ax.set_title('Uncertainty Proxy Metrics (Lower is Better)')
ax.set_ylabel('Metric Value')
ax.grid(axis='y', alpha=0.25)
plt.tight_layout()
calib_path = PLOT_DIR / 'uncertainty_proxy_metrics.png'
plt.savefig(calib_path, dpi=200, bbox_inches='tight')
if OUTPUT_ROOT != PLOT_DIR:
    plt.savefig(OUTPUT_ROOT / 'uncertainty_proxy_metrics.png', dpi=200, bbox_inches='tight')
plt.show()
plt.close(fig)
print('Saved training comparison plots to:', PLOT_DIR)

Saved training comparison plots to: /kaggle/working/results/training_plots

## 7.5 — Confusion Matrices

In [22]:
class_ticks = [str(i + 1) for i in range(num_classes)]
fig, axes   = plt.subplots(1, len(model_artifacts), figsize=(7 * len(model_artifacts), 5.5))

if len(model_artifacts) == 1:
    axes = [axes]

for ax, (model_name, artifact) in zip(axes, model_artifacts.items()):
    sns.heatmap(
        artifact['confusion_matrix'], annot=True, fmt='d', cmap='Blues',
        xticklabels=class_ticks, yticklabels=class_ticks, cbar=False, ax=ax,
    )
    ax.set_title(f'{model_name} Confusion Matrix')
    ax.set_xlabel('Predicted')
    ax.set_ylabel('True')

plt.tight_layout()
cm_path = PLOT_DIR / 'confusion_matrices_side_by_side.png'
plt.savefig(cm_path, dpi=220, bbox_inches='tight')
if OUTPUT_ROOT != PLOT_DIR:
    plt.savefig(OUTPUT_ROOT / 'confusion_matrices_side_by_side.png', dpi=220, bbox_inches='tight')
plt.show()
plt.close(fig)
print('Saved confusion matrix figure:', cm_path)

Saved confusion matrix figure: /kaggle/working/results/training_plots/confusion_matrices_side_by_side.png

# 8.0 — Scene Visualisation & Classification Maps

Loads saved models, runs full-scene patch-by-patch inference, and exports classification maps as individual PNGs, a combined overview PNG, and an Excel workbook.

## 8.1 — Visualisation Helper Functions

In [23]:
# Custom objects dict required for loading serialised models
VIS_CUSTOM_OBJECTS = {
    'PatchExtractor':       PatchExtractor,
    'PatchPositionEncoder': PatchPositionEncoder,
    'GlobalFilterLayer':    GlobalFilterLayer,
    'PatchEncoderWithCLS':  PatchEncoderWithCLS,
}


def get_scene_rgb(x_img, bands):
    """Select three representative spectral bands to form an approximate RGB composite."""
    if bands >= 6:
        rgb_idx = [bands // 2 - 1, bands // 2, bands // 2 + 1]
    elif bands >= 3:
        rgb_idx = [0, 1, 2]
    else:
        raise ValueError(f'Need at least 3 bands to form RGB, got {bands}.')
    return np.clip(x_img[:, :, rgb_idx], 0.0, 1.0)


def get_display_cmap(num_classes):
    """Return a ListedColormap with black background plus one colour per class."""
    return ListedColormap([BACKGROUND_COLOR] + get_class_colors(num_classes))


def predict_full_scene_labels(model, x_img, patch_size=9, batch_size=256):
    """Run patch-by-patch inference over the full scene and return a class-label map (1..K)."""
    pad   = patch_size // 2
    x_pad = np.pad(x_img, ((pad, pad), (pad, pad), (0, 0)), mode='edge')
    preds = np.zeros((x_img.shape[0], x_img.shape[1]), dtype=np.int32)

    for r in range(x_img.shape[0]):
        row_patches = np.empty(
            (x_img.shape[1], patch_size, patch_size, x_img.shape[-1]), dtype=np.float32,
        )
        for c in range(x_img.shape[1]):
            row_patches[c] = x_pad[r:r + patch_size, c:c + patch_size, :]
        row_prob  = model.predict(row_patches, batch_size=batch_size, verbose=0)
        preds[r]  = np.argmax(row_prob, axis=1) + 1   # back to 1..K

    return preds


def load_saved_models_for_visualization(model_dir, custom_objects):
    """Attempt to load best-checkpoint, final, or ensemble member 1 .keras files.
    
    Robust lookup order for each architecture:
    1. Unindexed best model in model_dir ({model}_best.keras)
    2. Unindexed final model in model_dir ({model}_final.keras)
    3. Member 1 final model in ensemble_dir or model_dir/ensembles ({model}_ens_1_final.keras)
    4. Member 1 best model in ensemble_dir or model_dir/ensembles ({model}_ens_1_best.keras)
    5. Search under OUTPUT_ROOT (flat or nested)
    6. Glob search fallback across all candidate directories
    """
    model_keys = ['AlexNet_CNN', 'GFNet', 'ViT_UNet']
    loaded, missing = {}, {}

    for model_key in model_keys:
        candidates = [
            model_dir / f'{model_key}_best.keras',
            model_dir / f'{model_key}_final.keras',
            model_dir / 'ensembles' / f'{model_key}_ens_1_final.keras',
            model_dir / 'ensembles' / f'{model_key}_ens_1_best.keras',
            ensemble_dir / f'{model_key}_ens_1_final.keras',
            ensemble_dir / f'{model_key}_ens_1_best.keras',
            OUTPUT_ROOT / 'models' / f'{model_key}_best.keras',
            OUTPUT_ROOT / 'models' / f'{model_key}_final.keras',
            OUTPUT_ROOT / 'models' / 'ensembles' / f'{model_key}_ens_1_final.keras',
            OUTPUT_ROOT / f'{model_key}_best.keras',
            OUTPUT_ROOT / f'{model_key}_final.keras',
            OUTPUT_ROOT / f'{model_key}_ens_1_final.keras',
        ]
        target_path = next((p for p in candidates if p.exists()), None)

        if target_path is None:
            # Defensive glob fallback across known model storage locations
            search_dirs = [model_dir, ensemble_dir, OUTPUT_ROOT, OUTPUT_ROOT / 'models', Path('/kaggle/working')]
            for s_dir in search_dirs:
                if s_dir.exists():
                    matches = (
                        sorted(s_dir.glob(f'**/{model_key}_ens_1_*.keras')) or
                        sorted(s_dir.glob(f'**/{model_key}_*.keras')) or
                        sorted(s_dir.glob(f'**/*{model_key}*.keras'))
                    )
                    if matches:
                        target_path = matches[0]
                        break

        if target_path is None or not target_path.exists():
            missing[model_key] = f'Missing .keras file for {model_key} in {model_dir} or {ensemble_dir}'
            continue

        try:
            print(f'Loading {model_key} for visualisation from: {target_path}')
            loaded[model_key] = keras.models.load_model(
                target_path, custom_objects=custom_objects, compile=False, safe_mode=False,
            )
            print(f'  -> Successfully loaded {model_key} ({loaded[model_key].name})')
        except Exception as exc:
            print(f'  -> Error loading {model_key} from {target_path}: {exc}')
            missing[model_key] = f'Load failed: {exc}'

    return loaded, missing


def save_single_panel(image, title, save_path, cmap=None, vmin=None, vmax=None):
    """Save a single image panel to PNG."""
    fig, ax = plt.subplots(figsize=(8, 6))
    if cmap is None:
        ax.imshow(image)
    else:
        ax.imshow(image, cmap=cmap, vmin=vmin, vmax=vmax)
    ax.set_title(title, fontsize=14)
    ax.axis('off')
    fig.tight_layout()
    fig.savefig(save_path, dpi=220, bbox_inches='tight')
    plt.show()
    plt.close(fig)
    print('Saved:', save_path)


def save_combined_overview(rgb_image, y_true, pred_maps, missing_info, num_classes, save_path):
    """Save a single figure with RGB, ground truth, and all three classification maps side-by-side."""
    cmap = get_display_cmap(num_classes)

    panels = [
        ('Approximate RGB',                 rgb_image,                    'rgb'),
        ('True Label Map',                  y_true,                       'label'),
        ('AlexNet Initial Classification',  pred_maps.get('AlexNet_CNN'), 'label'),
        ('GFNet Initial Classification',    pred_maps.get('GFNet'),       'label'),
        ('ViT Initial Classification',      pred_maps.get('ViT_UNet'),    'label'),
    ]

    fig, axes = plt.subplots(1, len(panels), figsize=(30, 7), sharex=True, sharey=True)
    for ax, (title, img, kind) in zip(axes, panels):
        ax.set_title(title, fontsize=13)
        if kind == 'rgb':
            ax.imshow(img)
        else:
            if img is None:
                ax.imshow(np.zeros_like(y_true), cmap=cmap, vmin=0, vmax=num_classes)
                # Determine which key is missing to show the correct error message
                key = next((k for k in ['AlexNet_CNN', 'GFNet', 'ViT_UNet'] if k in title), None)
                ax.text(0.5, 0.5, missing_info.get(key, 'Unavailable'),
                        ha='center', va='center', fontsize=10, wrap=True, transform=ax.transAxes)
            else:
                ax.imshow(img, cmap=cmap, vmin=0, vmax=num_classes)
        ax.axis('off')

    handles = [plt.Rectangle((0, 0), 1, 1, color=BACKGROUND_COLOR, label='Background')]
    class_colors = get_class_colors(num_classes)
    for i in range(num_classes):
        handles.append(plt.Rectangle((0, 0), 1, 1, color=class_colors[i], label=f'Class {i+1}'))
    fig.legend(handles=handles, loc='lower center', ncol=min(num_classes + 1, 8),
               bbox_to_anchor=(0.5, -0.02), frameon=True)
    fig.tight_layout(rect=[0, 0.05, 1, 1])
    fig.savefig(save_path, dpi=220, bbox_inches='tight')
    plt.show()
    plt.close(fig)
    print('Saved:', save_path)


def save_images_to_excel(excel_path, image_paths, sheet_name='Initial_Classification_Maps'):
    """Embed PNG images into an Excel workbook sheet at predefined anchor cells."""
    if excel_path.exists():
        wb = load_workbook(excel_path)
        if sheet_name in wb.sheetnames:
            del wb[sheet_name]
        ws = wb.create_sheet(title=sheet_name)
    else:
        wb = Workbook()
        ws = wb.active
        ws.title = sheet_name

    anchors = ['A1', 'J1', 'A25', 'J25', 'A49', 'J49']
    for path, anchor in zip(image_paths, anchors):
        if path.exists():
            img        = XLImage(str(path))
            img.anchor = anchor
            ws.add_image(img)

    wb.save(excel_path)
    print('Saved Excel workbook:', excel_path)

## 8.2 — Load Models & Generate Classification Maps

In [24]:
scene_rgb    = get_scene_rgb(x_img, B)
display_cmap = get_display_cmap(num_classes)

loaded_models, missing_models = load_saved_models_for_visualization(MODEL_DIR, VIS_CUSTOM_OBJECTS)
prediction_maps = {}

for model_key, loaded_model in loaded_models.items():
    print(f'Generating full-scene classified image for {model_key}...')
    prediction_maps[model_key] = predict_full_scene_labels(
        loaded_model, x_img, patch_size=PATCH_SIZE, batch_size=BATCH_SIZE,
    )
    print(f'{model_key} map shape:', prediction_maps[model_key].shape)

if missing_models:
    print('Some models could not be loaded:')
    for model_key, reason in missing_models.items():
        print(f'  - {model_key}: {reason}')

# Clean up models and clear session to prevent memory retention
del loaded_models
tf.keras.backend.clear_session()
gc.collect()

Loading AlexNet_CNN for visualisation from: /kaggle/working/results/models/AlexNet_CNN_best.keras
  -> Successfully loaded AlexNet_CNN (AlexNet_SingleHead)
Loading GFNet for visualisation from: /kaggle/working/results/models/GFNet_best.keras

/usr/local/lib/python3.12/dist-packages/keras/src/layers/layer.py:424: UserWarning: `build()` was called on layer 'gf_patch_encoder', however the layer does not have a `build()` method implemented and it looks like it has unbuilt state. This will cause the layer to be marked as built, despite not being actually built, which may cause failures down the line. Make sure to implement a proper `build()` method.
  warnings.warn(

  -> Successfully loaded GFNet (GFNet_SingleHead)
Loading ViT_UNet for visualisation from: /kaggle/working/results/models/ViT_UNet_best.keras
  -> Successfully loaded ViT_UNet (ViT_UNet_SingleHead)
Generating full-scene classified image for AlexNet_CNN...
AlexNet_CNN map shape: (512, 512)
Generating full-scene classified image for GFNet...
GFNet map shape: (512, 512)
Generating full-scene classified image for ViT_UNet...
ViT_UNet map shape: (512, 512)

0

## 8.3 — Save PNGs & Excel Workbook

In [25]:
rgb_png      = VIS_DIR / 'scene_rgb.png'
gt_png       = VIS_DIR / 'ground_truth_label_map.png'
alex_png     = VIS_DIR / 'AlexNet_CNN_initial_classification.png'
gfnet_png    = VIS_DIR / 'GFNet_initial_classification.png'
vit_png      = VIS_DIR / 'ViT_UNet_initial_classification.png'
overview_png = VIS_DIR / 'combined_initial_classification_overview.png'

save_single_panel(scene_rgb, 'Approximate RGB', rgb_png)
save_single_panel(y_img, 'Ground Truth Label Map', gt_png,
                  cmap=display_cmap, vmin=0, vmax=num_classes)

if prediction_maps.get('AlexNet_CNN') is not None:
    save_single_panel(prediction_maps['AlexNet_CNN'], 'AlexNet Initial Classification',
                      alex_png, cmap=display_cmap, vmin=0, vmax=num_classes)

if prediction_maps.get('GFNet') is not None:
    save_single_panel(prediction_maps['GFNet'], 'GFNet Initial Classification',
                      gfnet_png, cmap=display_cmap, vmin=0, vmax=num_classes)

if prediction_maps.get('ViT_UNet') is not None:
    save_single_panel(prediction_maps['ViT_UNet'], 'ViT Initial Classification',
                      vit_png, cmap=display_cmap, vmin=0, vmax=num_classes)

save_combined_overview(
    rgb_image=scene_rgb, y_true=y_img,
    pred_maps=prediction_maps, missing_info=missing_models,
    num_classes=num_classes, save_path=overview_png,
)

image_paths_for_excel = [rgb_png, gt_png, alex_png, gfnet_png, vit_png, overview_png]
save_images_to_excel(VIS_EXCEL_PATH, image_paths_for_excel,
                     sheet_name='Initial_Classification_Maps')

if OUTPUT_ROOT != VIS_DIR:
    shutil.copy(overview_png, OUTPUT_ROOT / overview_png.name)
    shutil.copy(VIS_EXCEL_PATH, OUTPUT_ROOT / VIS_EXCEL_PATH.name)

print('All visualisation outputs saved in:', VIS_DIR)

Saved: /kaggle/working/results/scene_visualizations/scene_rgb.png
Saved: /kaggle/working/results/scene_visualizations/ground_truth_label_map.png
Saved: /kaggle/working/results/scene_visualizations/AlexNet_CNN_initial_classification.png
Saved: /kaggle/working/results/scene_visualizations/GFNet_initial_classification.png
Saved: /kaggle/working/results/scene_visualizations/ViT_UNet_initial_classification.png
Saved: /kaggle/working/results/scene_visualizations/combined_initial_classification_overview.png
Saved Excel workbook: /kaggle/working/results/scene_visualizations/initial_classification_maps.xlsx
All visualisation outputs saved in: /kaggle/working/results/scene_visualizations

# 9.0 — Model Reload Utility

Convenience cell for loading any saved `.keras` model from Drive for downstream uncertainty analysis without retraining.

In [26]:
example_path = MODEL_DIR / 'ViT_UNet_final.keras'
if not example_path.exists():
    candidates = [
        MODEL_DIR / 'ViT_UNet_best.keras',
        ensemble_dir / 'ViT_UNet_ens_1_final.keras',
        ensemble_dir / 'ViT_UNet_ens_1_best.keras',
        OUTPUT_ROOT / 'ViT_UNet_ens_1_final.keras',
        OUTPUT_ROOT / 'models' / 'ViT_UNet_ens_1_final.keras',
        OUTPUT_ROOT / 'models' / 'ViT_UNet_best.keras',
        MODEL_DIR / 'ensembles' / 'ViT_UNet_ens_1_final.keras',
    ]
    glob_candidates = (
        sorted(MODEL_DIR.glob('**/ViT_UNet*.keras')) or
        sorted(OUTPUT_ROOT.glob('**/ViT_UNet*.keras')) or
        sorted(Path('/kaggle/working').glob('**/ViT_UNet*.keras'))
    )
    candidates.extend(glob_candidates)
    example_path = next((p for p in candidates if p.exists()), example_path)

if example_path.exists():
    loaded_model = keras.models.load_model(
        example_path, custom_objects=VIS_CUSTOM_OBJECTS,
        compile=False, safe_mode=False,
    )
    print('Loaded:', example_path)
    print('Model name:', loaded_model.name)
    del loaded_model
    tf.keras.backend.clear_session()
    gc.collect()
else:
    print('Example model not found. Train first, then reload.')

Loaded: /kaggle/working/results/models/ViT_UNet_final.keras
Model name: ViT_UNet_SingleHead